services:
  webserver:
    image: wordpress
    volumes:
      - ../backend/src/php:/var/www/html
    restart: always
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: user_password
      WORDPRESS_DB_NAME: example_db
    logging:
      driver: local

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: user_password
    logging:
      driver: local
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d

volumes:
  db:

